version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=dev_user
      - RABBITMQ_DEFAULT_PASS=dev_secret

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./php_myorm/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=secret", "--host=127.0.0.1", "ping", "--silent"]
      interval: 5s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]

# for a production deployment, xdebug should be disabled here
  backend_php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9004:9004"
    volumes:
      - .:/app:delegated
    environment:
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
    depends_on:
      - rabbitmq
      - mysql

  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/work.nginx:/etc/nginx/sites-enabled/work.nginx
    depends_on:
      - backend_php
